CREATE TABLE AUTOTESTCOMMODITY (
  COMMODITY_ID VARCHAR2(40) DEFAULT '' NOT NULL,
  COMMODITY_NAME VARCHAR2(4000) DEFAULT '' NOT NULL,
  COMMODITY_CODE VARCHAR2(40) DEFAULT '',
  APPLY_START_DATE VARCHAR2(200) DEFAULT '',
  UPC VARCHAR2(13) DEFAULT '',
  EXPIRATION_DATE VARCHAR2(200) DEFAULT '',
  QTY_PER_UNIT INT DEFAULT 0 NOT NULL,
  OTHER_ATTRIBUTES VARCHAR2(4000) DEFAULT '',
  PROGRAM_ID VARCHAR2(4000) DEFAULT '',
  CREATE_DATE_TIME TIMESTAMP,
  CREATE_USER_ID VARCHAR2(200) DEFAULT '',
  PRIMARY KEY (COMMODITY_ID)
);